# Generated by Django 5.2.11 on 2026-03-14 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventory', '0003_remove_location_uniq_location_org_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='membership',
            name='uniq_membership_org_user',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='org',
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['user__username']},
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
