# Generated by Django 5.2.11 on 2026-03-14 14:21

from django.db import migrations


def cleanup_org_permissions(apps, schema_editor):
    """Remove stale Organization ContentType and its permissions."""
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    ct = ContentType.objects.filter(app_label="accounts", model="organization").first()
    if ct:
        Permission.objects.filter(content_type=ct).delete()
        ct.delete()


def create_manager_group(apps, schema_editor):
    """Create Manager group with all inventory permissions."""
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    group, _ = Group.objects.get_or_create(name="Manager")

    # Add all inventory app permissions (product, location, stockmove)
    inventory_cts = ContentType.objects.filter(app_label="inventory")
    inventory_perms = Permission.objects.filter(content_type__in=inventory_cts)
    group.permissions.set(inventory_perms)


def reverse_create_manager_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name="Manager").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_manager_role'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(cleanup_org_permissions, migrations.RunPython.noop),
        migrations.RunPython(create_manager_group, reverse_create_manager_group),
    ]
