# Generated by Django 5.2.11 on 2026-03-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_cleanup_org_and_create_manager_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff'), ('staff0', 'Staff (view only)')], default='staff', max_length=10),
        ),
    ]
