# Generated by Django 5.2.11 on 2026-03-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_accessory_price'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='location',
            name='uniq_location_org_name',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='uniq_product_org_sku',
        ),
        migrations.RemoveField(
            model_name='location',
            name='org',
        ),
        migrations.RemoveField(
            model_name='product',
            name='org',
        ),
        migrations.RemoveField(
            model_name='stockmove',
            name='org',
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
