# Generated by Django 5.2.11 on 2026-03-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_location_uniq_location_org_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reorder_level',
        ),
        migrations.AddField(
            model_name='product',
            name='custom_size',
            field=models.CharField(blank=True, help_text="Number/custom value when size is 'Custom'", max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2XL', '2XL'), ('3XL', '3XL'), ('custom', 'Custom')], max_length=100),
        ),
    ]
