# Generated by Django 5.2.11 on 2026-03-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_size_choices_image_no_reorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop_code',
            field=models.CharField(blank=True, max_length=64, verbose_name='Shop Code'),
        ),
    ]
