# Generated by Django 5.2.11 on 2026-03-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_stockmove_price_tier_daily_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyvoucher',
            name='payment_date',
            field=models.DateField(blank=True, help_text='Date the payment was made (may differ from voucher date).', null=True),
        ),
        migrations.AlterField(
            model_name='dailyvoucher',
            name='payment_method',
            field=models.CharField(choices=[('kpay', 'KPay'), ('kbzBank', 'KBZ Bank'), ('kpay_kbzBank', 'KPay + KBZ Bank'), ('cash', 'Cash')], max_length=20),
        ),
    ]
