# Generated by Django 5.2.11 on 2026-03-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_stockmove_void_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmove',
            name='qty_delta',
            field=models.IntegerField(),
        ),
    ]
