# Generated by Django 5.2.11 on 2026-03-17 11:34

import datetime
from django.db import migrations, models


def backfill_move_date(apps, schema_editor):
    """Set move_date from created_at for all existing rows."""
    StockMove = apps.get_model("inventory", "StockMove")
    for move in StockMove.objects.filter(move_date__isnull=True).iterator():
        move.move_date = move.created_at.date()
        move.save(update_fields=["move_date"])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_qty_delta_integer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmove',
            options={'ordering': ['-move_date', '-created_at']},
        ),
        # Step 1: Add as nullable
        migrations.AddField(
            model_name='stockmove',
            name='move_date',
            field=models.DateField(null=True),
        ),
        # Step 2: Backfill from created_at
        migrations.RunPython(backfill_move_date, migrations.RunPython.noop),
        # Step 3: Set default and remove null
        migrations.AlterField(
            model_name='stockmove',
            name='move_date',
            field=models.DateField(default=datetime.date.today, help_text='Business date of this move. Defaults to today if not specified.'),
        ),
        migrations.AlterField(
            model_name='stockmove',
            name='price_tier',
            field=models.CharField(blank=True, choices=[('sp1', 'Selling Price 1'), ('sp2', 'Selling Price 2')], help_text='Applicable only for sale moves.', max_length=20),
        ),
    ]
